/**
 * 
 */
package com.vaadin.graphics.canvas;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.graphics.canvas.widgetset.client.Point;
import com.vaadin.graphics.canvas.widgetset.client.Rect;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

/**
 * @author kapil - kapil.verma@globallogic.com
 *
 */
public class CanvasComposite extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Canvas canvas;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public CanvasComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		
		Rect rect = new Rect(new Point(100, 200), new Point(300, 400));
		rect.setColor("#ff0000");
		rect.setFillColor("#0082ff");
		rect.setBorderWidth(4);
		rect.draw(canvas);
		
		rect = new Rect(new Point(500, 700), new Point(600, 800));
		rect.setColor("#0000ff");
		rect.setFillColor("#0082ff");
		rect.setBorderWidth(4);
		rect.draw(canvas);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// canvas
		canvas = new Canvas();
		canvas.setImmediate(false);
		canvas.setWidth("100.0%");
		canvas.setHeight("100.0%");
		mainLayout.addComponent(canvas, "top:0.0px;left:0.0px;");
		
		return mainLayout;
	}

}
